name: "example_pipeline_with_filter"

stages:
  # Stage 1: Read from Hugging Face dataset, calculate metrics, and filter
  - name: "score_and_filter"
    input:
      source:
        type: "huggingface"
        path: "/Users/duoan/Downloads/unsupervised-00000-of-00001.parquet"
        streaming: false
    operators:
      # Annotate with textstat metrics, then filter
      - "textstat-annotator"
      - "textstat-filter":
          column: "text"
          metrics:
            flesch_reading_ease:
              min: 0
              max: 100
            automated_readability_index:
              min: 0
              max: 100
            syllable_count:
              min: 32.0
              max: 2331.9
            lexicon_count:
              min: 23.0
              max: 1554.0
            sentence_count:
              min: 1.0
              max: 89.1
            character_count:
              min: 118.0
              max: 7466.3
            letter_count:
              min: 109.0
              max: 7193.0
            polysyllable_count:
              min: 0.0
              max: 216.4
            monosyllable_count:
              min: 13.0
              max: 1044.1
            difficult_words:
              min: 4.0
              max: 213.4
    output:
      source:
        type: "parquet"
        path: "./example_data/filtered_output"
