source:
  kind: parquet
  uris:
    - /Users/duoan/Downloads/unsupervised-00000-of-00001.parquet
  columns:
    id: id
    text: text

pipeline:
  - op: text.normalize
    config:
      text_col: text
      lowercase: true
      strip: true

  - op: text.len_filter
    config:
      text_col: text
      lower_bound: 20
      upper_bound: 50000

  # Gopher filters - not yet implemented in Rust
  # - op: text.gopher_quality_filter
  #   config:
  #     text_col: text_norm
  #     min_doc_words: 50
  #     max_doc_words: 100000
  #     min_avg_word_length: 3.0
  #     max_avg_word_length: 10.0
  #     max_symbol_word_ratio: 0.1
  #     max_bullet_lines_ratio: 0.9
  #     max_ellipsis_lines_ratio: 0.3
  #     max_non_alpha_words_ratio: 0.8
  #     min_stop_words: 2

  # - op: text.gopher_repetition_filter
  #   config:
  #     text_col: text_norm
  #     dup_line_frac: 0.3
  #     dup_para_frac: 0.3
  #     dup_line_char_frac: 0.2
  #     dup_para_char_frac: 0.2
  #     top_n_grams:
  #       - [2, 0.2]
  #       - [3, 0.18]
  #       - [4, 0.16]
  #     dup_n_grams:
  #       - [5, 0.15]
  #       - [6, 0.14]
  #       - [7, 0.13]
  #       - [8, 0.12]
  #       - [9, 0.11]
  #       - [10, 0.10]

  - op: text.special_char_ratio
    config:
      text_col: text
      out_col: special_ratio

  - op: filter.leq
    config:
      col: special_ratio
      value: 0.30

  # FastText classifier filter (optional, requires model file)
  # - op: text.fasttext_classifier_filter
  #   config:
  #     text_col: text_norm
  #     model_path: ./models/lid.176.bin
  #     keep_labels:
  #       - ["en", 0.9]
  #     save_labels_in_metadata: true
  #     filter_mode: "document"
  #     k: -1
  #     threshold: 0.0

sink:
  kind: parquet
  uri: ./output/filtered.parquet
  mode: overwrite
