source:
  kind: parquet
  uris:
    - /Users/duoan/Downloads/unsupervised-00000-of-00001.parquet
  columns:
    id: id
    text: text

pipeline:
  - add_id:
      id_col: "uuid"
  - text_normalize_transformer:
      text_col: text
      lowercase: true
      strip: true

  - text_len_filter:
      text_col: text
      lower_bound: 20
      upper_bound: 2000

  # Symbol ratio filter - adjust threshold based on your data
  - text_symbol_ratio_filter:
      text_col: text
      max_symbol_to_word_ratio: 0.30

sink:
  kind: jsonline
  uri: ./output/
  mode: overwrite
  # Trace and error outputs are automatically enabled:
  # - output/trace/step_xx/ for documents filtered at each step
  # - output/final/ for documents that passed all filters
  # - output/error/ for documents that failed to parse
