source:
  kind: huggingface
  uris:
    - HuggingFaceFW/fineweb-edu/blob/main/sample/10BT/000_00000.parquet
  columns:
    id: id
    text: text
  batch_size: 1000000

pipeline:
  - add_id:
      id_col: "uuid"
  - text_normalize_transformer:
      text_col: text
      lowercase: true
      strip: true

  - text_len_filter:
      text_col: text
      lower_bound: 20
      upper_bound: 2000

  # Symbol ratio filter - adjust threshold based on your data
  - text_symbol_ratio_filter:
      text_col: text
      max_symbol_to_word_ratio: 0.30

sink:
  kind: parquet
  uri: ./output/
  mode: overwrite
  samples_per_shard: 10000
  enable_trace: false
  # Trace and error outputs are automatically enabled:
  # - output/trace/step_xx/ for documents filtered at each step
  # - output/final/ for documents that passed all filters
  # - output/error/ for documents that failed to parse
